apiVersion: v1
kind: Service
metadata:
  name: products-mongo
  labels:
    app: products-mongo
  namespace: micro
spec:
  ports:
    - port: 27017
  selector:
    app: products-mongo
  clusterIP: None