apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: products
  labels:
    app: product
  namespace: micro
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi