// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/product.proto

package product

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Product service

func NewProductEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Product service

type ProductService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	CreateProduct(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error)
	GetProduct(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error)
	DeleteProduct(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
}

type productService struct {
	c    client.Client
	name string
}

func NewProductService(name string, c client.Client) ProductService {
	return &productService{
		c:    c,
		name: name,
	}
}

func (c *productService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Product.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) CreateProduct(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.name, "Product.CreateProduct", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.name, "Product.List", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) GetProduct(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error) {
	req := c.c.NewRequest(c.name, "Product.GetProduct", in)
	out := new(GetResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) DeleteProduct(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.name, "Product.DeleteProduct", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Product service

type ProductHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	CreateProduct(context.Context, *CreateRequest, *CreateResponse) error
	List(context.Context, *ListRequest, *ListResponse) error
	GetProduct(context.Context, *GetRequest, *GetResponse) error
	DeleteProduct(context.Context, *DeleteRequest, *DeleteResponse) error
}

func RegisterProductHandler(s server.Server, hdlr ProductHandler, opts ...server.HandlerOption) error {
	type product interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		CreateProduct(ctx context.Context, in *CreateRequest, out *CreateResponse) error
		List(ctx context.Context, in *ListRequest, out *ListResponse) error
		GetProduct(ctx context.Context, in *GetRequest, out *GetResponse) error
		DeleteProduct(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error
	}
	type Product struct {
		product
	}
	h := &productHandler{hdlr}
	return s.Handle(s.NewHandler(&Product{h}, opts...))
}

type productHandler struct {
	ProductHandler
}

func (h *productHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.ProductHandler.Call(ctx, in, out)
}

func (h *productHandler) CreateProduct(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.ProductHandler.CreateProduct(ctx, in, out)
}

func (h *productHandler) List(ctx context.Context, in *ListRequest, out *ListResponse) error {
	return h.ProductHandler.List(ctx, in, out)
}

func (h *productHandler) GetProduct(ctx context.Context, in *GetRequest, out *GetResponse) error {
	return h.ProductHandler.GetProduct(ctx, in, out)
}

func (h *productHandler) DeleteProduct(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.ProductHandler.DeleteProduct(ctx, in, out)
}
